BATTERY_MODES = (
    "Not present",
    "Standby",
    "Discharge",
    "Charge",
    "To be charged",
    "To be discharged",
)

ENERGY_MODES = (
    "Check Mode",
    "Wait Mode",
    "Normal (On-Grid)",
    "Normal (Off-Grid)",
    "Flash Mode",
    "Fault Mode",
    "Battery Standby",
    "Battery Charging",
    "Battery Discharging",
)

GRID_MODES = (
    "Not connected",
    "Connected",
    "Fault",
)

GRID_IN_OUT_MODES = (
    "Idle",
    "Exporting",
    "Importing",
)

LOAD_MODES = (
    "Disconnected",
    "Connected",
)

PV_MODES = (
    "Panels not connected",
    "Panels connected, no power",
    "Panels connected, producing power",
)

WORK_MODES = (
    "Standby",
    "Normal",
    "Error",
    "Check Mode",
)

SAFETY_COUNTRIES: dict[int, str] = {
    0: "Italy",
    1: "Czechia",
    2: "Germany",
    3: "Spain",
    4: "Greece Mainland",
    5: "Denmark",
    6: "Belgium",
    7: "Romania",
    8: "G98",
    9: "Australia",
    10: "France",
    11: "China",
    12: "60Hz Grid Default",
    13: "Poland",
    14: "South Africa",
    15: "AustraliaL",
    16: "Brazil",
    17: "Thailand MEA",
    18: "Thailand PEA",
    19: "Mauritius",
    20: "Holland",
    21: "G99",
    22: "China Special",
    23: "French 50Hz",
    24: "French 60Hz",
    25: "Australia Ergon",
    26: "Australia Energex",
    27: "Holland 16/20A",
    28: "Korea",
    29: "China Station",
    30: "Austria",
    31: "India",
    32: "50Hz Grid Default",
    33: "Warehouse",
    34: "Philippines",
    35: "Ireland",
    36: "Taiwan",
    37: "Bulgaria",
    38: "Barbados",
    39: "China Special High",
    40: "G99",
    41: "Sweden",
    42: "Chile",
    43: "Brazil LV",
    44: "NewZealand",
    45: "IEEE1547 208VAC",
    46: "IEEE1547 220VAC",
    47: "IEEE1547 240VAC",
    48: "60Hz LV Default",
    49: "50Hz LV Default",
    50: "AU_WAPN",
    51: "AU_MicroGrid",
    52: "JP_50Hz",
    53: "JP_60Hz",
    54: "India Higher",
    55: "DEWA LV",
    56: "DEWA MV",
    57: "Slovakia",
    58: "GreenGrid",
    59: "Hungary",
    60: "Sri Lanka",
    61: "Spain Islands",
    62: "Ergon30K",
    63: "Energex30K",
    64: "IEEE1547 230/400V",
    65: "IEC61727 60Hz",
    66: "Switzerland",
    67: "CEI-016",
    68: "AU_Horizon",
    69: "Cyprus",
    70: "AU_SAPN",
    71: "AU_Ausgrid",
    72: "AU_Essential",
    73: "AU_Pwcore&CitiPW",
    74: "Hong Kong",
    75: "Poland MV",
    76: "Holland MV",
    77: "Sweden MV",
    78: "VDE4110",
    96: "cUSA_208VacDefault",
    97: "cUSA_240VacDefault",
    98: "cUSA_208VacCA_SCE",
    99: "cUSA_240VacCA_SCE",
    100: "cUSA_208VacCA_SDGE",
    101: "cUSA_240VacCA_SDGE",
    102: "cUSA_208VacCA_PGE",
    103: "cUSA_240VacCA_PGE",
    104: "cUSA_208VacHECO_14HO",
    105: "cUSA_240VacHECO_14HO0x69",
    106: "cUSA_208VacHECO_14HM",
    107: "cUSA_240VacHECO_14HM",
}

ERROR_CODES = (
    "GFCI Device Check Failure",
    "AC HCT Check Failure",
    "",
    "DCI Consistency Failure",
    "GFCI Consistency Failure",
    "",
    "GFCI Device Failure",
    "Relay Device Failure",
    "AC HCT Failure",
    "Utility Loss",
    "Ground I Failure",
    "DC Bus High",
    "InternalFan Failure",
    "Over Temperature",
    "Utility Phase Failure",
    "PV Over Voltage",
    "External Fan Failure",
    "Vac Failure",
    "Isolation Failure",
    "DC Injection High",
    "Back-Up Over Load",
    "",
    "Fac Consistency Failure",
    "Vac Consistency Failure",
    "",
    "Relay Check Failure",
    "",
    "PhaseAngleFailure",
    "DSP communication failure",
    "Fac Failure",
    "EEPROM R/W Failure",
    "Internal Communication Failure",
)

DIAG_STATUS_CODES = (
    "Battery voltage low",
    "Battery SOC low",
    "Battery SOC in back",
    "BMS: Discharge disabled",
    "Discharge time on",
    "Charge time on",
    "Discharge Driver On",
    "BMS: Discharge current low",
    "APP: Discharge current too low",
    "Meter communication failure",
    "Meter connection reversed",
    "Self-use load light",
    "EMS: discharge current is zero",
    "Discharge BUS high PV voltage",
    "Battery Disconnected",
    "Battery Overcharged",
    "BMS: Temperature too high",
    "BMS: Charge too high",
    "BMS: Charge disabled",
    "Self-use off",
    "SOC delta too volatile",
    "Battery self discharge too high",
    "Battery SOC low (off-grid)",
    "Grid wave unstable",
    "Export power limit set",
    "PF value set",
    "Real power limit set",
    "DC output on",
    "SOC protect off",
)

BMS_ALARM_CODES = (
    "Charging over-voltage 2",
    "Discharging under-voltage 2",
    "Cell temperature high 2",
    "Cell temperature low 2",
    "Charging over-current 2",
    "Discharging over-current 2",
    "Precharge fault",
    "DC bus fault",
    "Battery break",
    "Battery lock",
    "Discharging circuit failure",
    "Charging circuit failure",
    "Communication failure 2",
    "Cell temperature high 3",
    "Discharging under-voltage 3",
    "Charging over-voltage 3",
)

BMS_WARNING_CODES = (
    "Charging over-voltage 1",
    "Discharging under-voltage 1",
    "Cell temperature high 1",
    "Cell temperature low 1",
    "Charging over-current 1",
    "Discharging over-current 1",
    "Communication failure 1",
    "System reboot",
    "Cell imbalance",
    "System temperature low 1",
    "System temperature low 2",
    "System temperature high",
)
